name: Build

on:
  push:
    branches:
      - "dev"
    paths:
      - "TimetableDesigner.Backend.Events.OutboxPattern**"
  pull_request:
    branches:
      - "dev"
      - "main"
    paths:
      - "TimetableDesigner.Backend.Events.OutboxPattern**"

jobs:
  build:
    name: Build
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Add package source
        run: dotnet nuget add source --name gitea --username TimetableDesigner --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text https://repos.mateuszskoczek.com/api/packages/TimetableDesigner/nuget/index.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Create NuGet package
        run: dotnet pack -c Debug --output ./